# Generated by Django 5.2.17 on 2026-10-05 16:58

import django.db.models.deletion
import django.db.models.manager
import pessoas.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPessoa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('arquivado', models.BooleanField(default=False, verbose_name='arquivado')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('tipo', models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], default='fisica', max_length=10, verbose_name='tipo')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, validators=[pessoas.validators.validar_cpf_cnpj], verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('rg_orgao_emissor', models.CharField(blank=True, max_length=20, verbose_name='órgão emissor do RG')),
                ('nacionalidade', models.CharField(blank=True, max_length=40, verbose_name='nacionalidade')),
                ('estado_civil', models.CharField(blank=True, max_length=40, verbose_name='estado civil')),
                ('profissao', models.CharField(blank=True, max_length=60, verbose_name='profissão')),
                ('representante_nome', models.CharField(blank=True, max_length=160, verbose_name='nome do representante')),
                ('representante_cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF do representante')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pessoa',
                'verbose_name_plural': 'historical pessoas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivado', models.BooleanField(default=False, verbose_name='arquivado')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('tipo', models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], default='fisica', max_length=10, verbose_name='tipo')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, validators=[pessoas.validators.validar_cpf_cnpj], verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('rg_orgao_emissor', models.CharField(blank=True, max_length=20, verbose_name='órgão emissor do RG')),
                ('nacionalidade', models.CharField(blank=True, max_length=40, verbose_name='nacionalidade')),
                ('estado_civil', models.CharField(blank=True, max_length=40, verbose_name='estado civil')),
                ('profissao', models.CharField(blank=True, max_length=60, verbose_name='profissão')),
                ('representante_nome', models.CharField(blank=True, max_length=160, verbose_name='nome do representante')),
                ('representante_cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF do representante')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome'],
                'abstract': False,
                'base_manager_name': 'todos',
                'default_manager_name': 'objetos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('arquivado', False), models.Q(('cpf_cnpj', ''), _negated=True)), fields=('cpf_cnpj',), name='cpf_cnpj_unico_entre_nao_arquivados')],
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
