# Generated by Django 5.2.17 on 2026-10-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_empresa_usuario_empresa'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpessoa',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
    ]
