# Generated by Django 5.2.17 on 2026-10-07 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_empresa_usuario_empresa'),
        ('pessoas', '0002_historicalpessoa_empresa_pessoa_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pessoa',
            name='cpf_cnpj_unico_entre_nao_arquivados',
        ),
        migrations.AddConstraint(
            model_name='pessoa',
            constraint=models.UniqueConstraint(condition=models.Q(('arquivado', False), models.Q(('cpf_cnpj', ''), _negated=True)), fields=('empresa', 'cpf_cnpj'), name='cpf_cnpj_unico_entre_nao_arquivados'),
        ),
    ]
