# Generated by Django 5.2.17 on 2026-10-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalveiculo',
            name='proprietario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.pessoa', verbose_name='proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='pessoas.pessoa', verbose_name='proprietário'),
        ),
    ]
