# Generated by Django 5.2.17 on 2026-10-07 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_empresa_usuario_empresa'),
        ('pessoas', '0003_remove_pessoa_cpf_cnpj_unico_entre_nao_arquivados_and_more'),
        ('veiculos', '0003_fotoveiculo_empresa_historicalfotoveiculo_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='veiculo',
            name='placa_unica_entre_nao_arquivados',
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('arquivado', False)), fields=('empresa', 'placa'), name='placa_unica_entre_nao_arquivados'),
        ),
    ]
