# Generated by Django 5.2.17 on 2026-10-05 20:38

import contratos.models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivado', models.BooleanField(default=False, verbose_name='arquivado')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('razao_social', models.CharField(blank=True, max_length=160, verbose_name='razão social')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('representante_nome', models.CharField(blank=True, max_length=160, verbose_name='representante')),
                ('representante_cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF do representante')),
                ('multa_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='multa por descumprimento (%)')),
                ('regra_ipva', models.CharField(blank=True, max_length=200, verbose_name='regra padrão de IPVA e licenciamento')),
                ('prazo_assinatura_dias', models.PositiveSmallIntegerField(default=5, verbose_name='prazo para assinar a ATPV-e (dias úteis)')),
                ('prazo_repasse_dias', models.PositiveSmallIntegerField(default=5, verbose_name='prazo de repasse ao consignante (dias úteis)')),
                ('numero_vias', models.PositiveSmallIntegerField(default=2, verbose_name='número de vias')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'configuração da loja',
                'verbose_name_plural': 'configuração da loja',
                'abstract': False,
                'base_manager_name': 'todos',
                'default_manager_name': 'objetos',
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracaoLoja',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('arquivado', models.BooleanField(default=False, verbose_name='arquivado')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('razao_social', models.CharField(blank=True, max_length=160, verbose_name='razão social')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('representante_nome', models.CharField(blank=True, max_length=160, verbose_name='representante')),
                ('representante_cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF do representante')),
                ('multa_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='multa por descumprimento (%)')),
                ('regra_ipva', models.CharField(blank=True, max_length=200, verbose_name='regra padrão de IPVA e licenciamento')),
                ('prazo_assinatura_dias', models.PositiveSmallIntegerField(default=5, verbose_name='prazo para assinar a ATPV-e (dias úteis)')),
                ('prazo_repasse_dias', models.PositiveSmallIntegerField(default=5, verbose_name='prazo de repasse ao consignante (dias úteis)')),
                ('numero_vias', models.PositiveSmallIntegerField(default=2, verbose_name='número de vias')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical configuração da loja',
                'verbose_name_plural': 'historical configuração da loja',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('arquivado', models.BooleanField(default=False, verbose_name='arquivado')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('termo_vistoria', 'Termo de vistoria e entrega'), ('recibo', 'Recibo'), ('consulta', 'Consulta de situação do veículo'), ('procuracao', 'Procuração/autorização'), ('doc_veiculo', 'Documento do veículo (CRV/CRLV)'), ('doc_pessoal', 'Documento pessoal'), ('outro', 'Outro')], max_length=16, verbose_name='tipo')),
                ('arquivo', models.TextField(max_length=100, verbose_name='arquivo')),
                ('gerado_pelo_sistema', models.BooleanField(default=False, verbose_name='gerado pelo sistema')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('consignacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='negocios.consignacao', verbose_name='consignação')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='negocios.negocio', verbose_name='negócio')),
            ],
            options={
                'verbose_name': 'historical documento',
                'verbose_name_plural': 'historical documentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivado', models.BooleanField(default=False, verbose_name='arquivado')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('termo_vistoria', 'Termo de vistoria e entrega'), ('recibo', 'Recibo'), ('consulta', 'Consulta de situação do veículo'), ('procuracao', 'Procuração/autorização'), ('doc_veiculo', 'Documento do veículo (CRV/CRLV)'), ('doc_pessoal', 'Documento pessoal'), ('outro', 'Outro')], max_length=16, verbose_name='tipo')),
                ('arquivo', models.FileField(upload_to=contratos.models.documento_upload_para, verbose_name='arquivo')),
                ('gerado_pelo_sistema', models.BooleanField(default=False, verbose_name='gerado pelo sistema')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('consignacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='negocios.consignacao', verbose_name='consignação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='negocios.negocio', verbose_name='negócio')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-criado_em'],
                'abstract': False,
                'base_manager_name': 'todos',
                'default_manager_name': 'objetos',
                'constraints': [models.CheckConstraint(condition=models.Q(('negocio__isnull', False), ('consignacao__isnull', False), _connector='OR'), name='documento_pertence_a_negocio_ou_consignacao')],
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
