# Generated by Django 5.2.17 on 2026-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_historicalcontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome fantasia'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaoloja',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome fantasia'),
        ),
    ]
