# Generated by Django 5.2.17 on 2026-10-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_configuracaoloja_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoloja',
            name='multa_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentagem cobrada de quem desistir ou descumprir o contrato. Combine o valor com o seu advogado. Ex.: 10', max_digits=5, null=True, verbose_name='multa se não cumprir o combinado (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='regra_ipva',
            field=models.CharField(blank=True, help_text='O que vale por padrão nos contratos. Ex.: até a entrega, por conta do vendedor; a partir da entrega, do comprador.', max_length=200, verbose_name='quem paga o IPVA e o licenciamento'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracaoloja',
            name='multa_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentagem cobrada de quem desistir ou descumprir o contrato. Combine o valor com o seu advogado. Ex.: 10', max_digits=5, null=True, verbose_name='multa se não cumprir o combinado (%)'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracaoloja',
            name='regra_ipva',
            field=models.CharField(blank=True, help_text='O que vale por padrão nos contratos. Ex.: até a entrega, por conta do vendedor; a partir da entrega, do comprador.', max_length=200, verbose_name='quem paga o IPVA e o licenciamento'),
        ),
    ]
