# Generated by Django 5.2.17 on 2026-10-06 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_configuracaoloja_multa_percentual_and_more'),
        ('negocios', '0001_initial'),
        ('veiculos', '0002_historicalveiculo_proprietario_veiculo_proprietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documento',
            name='documento_pertence_a_negocio_ou_consignacao',
        ),
        migrations.AddField(
            model_name='documento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='veiculos.veiculo', verbose_name='veículo'),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='veiculo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='veiculos.veiculo', verbose_name='veículo'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('negocio__isnull', False), ('consignacao__isnull', False), ('veiculo__isnull', False), _connector='OR'), name='documento_pertence_a_negocio_ou_consignacao'),
        ),
    ]
