# Generated by Django 5.2.17 on 2026-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_remove_documento_documento_pertence_a_negocio_ou_consignacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='num_testemunhas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='nº de testemunhas'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='num_testemunhas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='nº de testemunhas'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
    ]
