# Generated by Django 5.2.17 on 2026-10-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_empresa_usuario_empresa'),
        ('contratos', '0006_contrato_num_testemunhas_contrato_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaoloja',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contas.empresa', verbose_name='empresa'),
        ),
    ]
